### ISSUE TITLE
Re-render the data

### ISSUE THREAD

**Issue by maybenat** [TIKramer/react-native-swipeable-deck#1]
Hey! Great package. Is there a way to re-render the data in the stack on the end of the stack reached?

**Comment by TIKramer** [comment]
Hi Natalie ThankYou!
Currently the only way to do this would be to keep a counter and increment in the swipe callbacks . 
onSwipeLeft - onSwipeRight - 

 const onSwipeLeft = (item: SwipeData) =>
  {
    setCounter(counter +1)
}

you could then reset the data for swipeList once the counter reaches the end length - The swipe list would rerender once the data prop is changed.
  useEffect(() => {
    // You have reached the end - reset the data.
    if(counter === data.length)
    {
      setData([...data])
    }
  },[counter]);



What I will do is add a callback -handleNoMoreCards() - which will make this easier
I may also add a refresh prop - to refresh automatically on end. 
Sometime next week.

Please let me know if you have any other suggestions, as this is a personal project of mine I am happy to add any new features to improve the library.

Thanks,
Thomas
